version: "3"

services:
  rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq-checkout
        ports:
            - 15672:15672
            - 5672:5672
            - 5671:5671
            - 4369:4369
  database:
        image: mongo
        container_name: checkout-mongo
        environment:
            - MONGO_INITDB_DATABASE=checkout-local
        ports:
            - 27017:27017
            - 27019:27019
  write-api:
        build: 
          context: ./src/
          dockerfile: $PWD/src/PaymentGateway.WriteModel.API/Dockerfile
        depends_on:
          - rabbitmq
        ports:
            - 5009:80
  acquiring-bank:
    build:
      context: ./src/
      dockerfile: $PWD/src/AcquiringBank.API/Dockerfile
    ports:
      - 6002:80